# Use root/example as user/password credentials
services:

  mongo:
    image: mongo:${DB_VERSION:-latest}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${DB_NAME:-dbmovie}
    ports:
      - ${DB_PORT:-27017}:27017
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d/

  mongo-express:
    image: mongo-express:${GUI_TAG:-latest}
    restart: always
    ports:
      - ${GUI_PORT:-8081}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_ROOT_USER:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_ROOT_PASSWORD:-password}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_ROOT_USER:-root}:${DB_ROOT_PASSWORD:-password}@mongo:27017/
      ME_CONFIG_BASICAUTH: false


